-- 스터디 20개 추가 SQL
-- 현재 사용자가 가입하지 않은 새로운 스터디들을 추가합니다.

-- 먼저 소유자 ID를 확인합니다 (여러 사용자 중에서 선택)
-- 실행 전에 SELECT id, name, email FROM "User" LIMIT 10; 로 사용자 ID를 확인하세요

-- 스터디 데이터 추가
-- ownerId는 실제 데이터베이스의 사용자 ID로 교체해야 합니다
-- 아래 예시에서는 'USER_ID_1', 'USER_ID_2' 등으로 표시했습니다

INSERT INTO "Study" (id, "ownerId", name, emoji, description, category, "subCategory", "maxMembers", "isPublic", "autoApprove", "isRecruiting", rating, "reviewCount", tags, "inviteCode", "createdAt", "updatedAt")
VALUES
-- 1. TypeScript 마스터클래스
('study_ts_master_001',
 (SELECT id FROM "User" WHERE email = 'lee@example.com' LIMIT 1),
 'TypeScript 마스터클래스',
 '📘',
 'TypeScript의 고급 타입 시스템부터 실전 프로젝트까지 완벽 마스터! 제네릭, 유틸리티 타입, 데코레이터 등을 심도있게 학습합니다.',
 '프로그래밍',
 '프론트엔드',
 15,
 true,
 false,
 true,
 4.8,
 23,
 ARRAY['TypeScript', '타입시스템', '고급'],
 'invite_ts_001',
 NOW() - INTERVAL '15 days',
 NOW() - INTERVAL '15 days'),

-- 2. Rust 시스템 프로그래밍
('study_rust_002',
 (SELECT id FROM "User" WHERE email = 'park@example.com' LIMIT 1),
 'Rust 시스템 프로그래밍',
 '🦀',
 'Rust로 안전하고 빠른 시스템 프로그래밍을 배웁니다. 소유권, 빌림, 생명주기를 완벽하게 이해하고 실전 프로젝트를 진행합니다.',
 '프로그래밍',
 '시스템',
 12,
 true,
 true,
 true,
 4.9,
 18,
 ARRAY['Rust', '시스템프로그래밍', '성능'],
 'invite_rust_002',
 NOW() - INTERVAL '20 days',
 NOW() - INTERVAL '20 days'),

-- 3. MongoDB 실전 가이드
('study_mongo_003',
 (SELECT id FROM "User" WHERE email = 'choi@example.com' LIMIT 1),
 'MongoDB 실전 가이드',
 '🍃',
 'NoSQL 데이터베이스 MongoDB를 실무 수준으로 마스터합니다. 인덱싱, 집계, 샤딩까지 모든 것을 다룹니다.',
 '프로그래밍',
 '데이터베이스',
 18,
 true,
 false,
 true,
 4.6,
 21,
 ARRAY['MongoDB', 'NoSQL', '데이터베이스'],
 'invite_mongo_003',
 NOW() - INTERVAL '10 days',
 NOW() - INTERVAL '10 days'),

-- 4. Redis 캐싱 전략
('study_redis_004',
 (SELECT id FROM "User" WHERE email = 'jung@example.com' LIMIT 1),
 'Redis 캐싱 전략',
 '⚡',
 'Redis를 활용한 고성능 캐싱 전략과 실시간 데이터 처리를 학습합니다. Pub/Sub, Streams까지 완벽 정복!',
 '프로그래밍',
 '백엔드',
 14,
 true,
 true,
 true,
 4.7,
 15,
 ARRAY['Redis', '캐싱', '성능최적화'],
 'invite_redis_004',
 NOW() - INTERVAL '12 days',
 NOW() - INTERVAL '12 days'),

-- 5. Next.js 13 App Router
('study_nextjs_005',
 (SELECT id FROM "User" WHERE email = 'kang@example.com' LIMIT 1),
 'Next.js 13 App Router 완전정복',
 '▲',
 'Next.js 13의 App Router와 Server Components를 활용한 최신 웹 개발을 배웁니다. RSC, Streaming까지!',
 '프로그래밍',
 '프론트엔드',
 16,
 true,
 false,
 true,
 4.9,
 28,
 ARRAY['Next.js', 'React', 'SSR'],
 'invite_nextjs_005',
 NOW() - INTERVAL '8 days',
 NOW() - INTERVAL '8 days'),

-- 6. gRPC 마이크로서비스
('study_grpc_006',
 (SELECT id FROM "User" WHERE email = 'han@example.com' LIMIT 1),
 'gRPC 마이크로서비스 아키텍처',
 '🔌',
 'gRPC를 활용한 고성능 마이크로서비스 구축. Protocol Buffers, 스트리밍, 인증/인가까지 학습합니다.',
 '프로그래밍',
 '백엔드',
 12,
 true,
 true,
 true,
 4.5,
 12,
 ARRAY['gRPC', '마이크로서비스', 'ProtoBuf'],
 'invite_grpc_006',
 NOW() - INTERVAL '18 days',
 NOW() - INTERVAL '18 days'),

-- 7. Terraform 인프라 자동화
('study_terraform_007',
 (SELECT id FROM "User" WHERE email = 'yoon@example.com' LIMIT 1),
 'Terraform 인프라 자동화',
 '🏗️',
 'IaC의 정석 Terraform으로 클라우드 인프라를 코드로 관리합니다. AWS, GCP, Azure 멀티 클라우드 지원!',
 '프로그래밍',
 'DevOps',
 15,
 true,
 false,
 true,
 4.8,
 19,
 ARRAY['Terraform', 'IaC', 'DevOps'],
 'invite_terraform_007',
 NOW() - INTERVAL '14 days',
 NOW() - INTERVAL '14 days'),

-- 8. WebAssembly 개발
('study_wasm_008',
 (SELECT id FROM "User" WHERE email = 'lim@example.com' LIMIT 1),
 'WebAssembly 고성능 웹 개발',
 '⚙️',
 'WebAssembly로 브라우저에서 네이티브 수준의 성능을 구현합니다. Rust/C++에서 WASM으로!',
 '프로그래밍',
 '웹개발',
 10,
 true,
 true,
 true,
 4.6,
 14,
 ARRAY['WebAssembly', 'WASM', '고성능'],
 'invite_wasm_008',
 NOW() - INTERVAL '22 days',
 NOW() - INTERVAL '22 days'),

-- 9. GitHub Actions CI/CD
('study_github_009',
 (SELECT id FROM "User" WHERE email = 'jang@example.com' LIMIT 1),
 'GitHub Actions로 완성하는 CI/CD',
 '🔄',
 'GitHub Actions를 활용한 자동화 파이프라인 구축. 테스트, 빌드, 배포를 자동화합니다.',
 '프로그래밍',
 'DevOps',
 18,
 true,
 true,
 true,
 4.7,
 22,
 ARRAY['GitHub Actions', 'CI/CD', '자동화'],
 'invite_github_009',
 NOW() - INTERVAL '9 days',
 NOW() - INTERVAL '9 days'),

-- 10. Svelte & SvelteKit
('study_svelte_010',
 (SELECT id FROM "User" WHERE email = 'oh@example.com' LIMIT 1),
 'Svelte & SvelteKit 실전',
 '🔥',
 '가장 간결한 프론트엔드 프레임워크 Svelte와 SvelteKit으로 빠르고 효율적인 웹 앱을 만듭니다.',
 '프로그래밍',
 '프론트엔드',
 14,
 true,
 false,
 true,
 4.8,
 17,
 ARRAY['Svelte', 'SvelteKit', '프론트엔드'],
 'invite_svelte_010',
 NOW() - INTERVAL '11 days',
 NOW() - INTERVAL '11 days'),

-- 11. Elasticsearch 검색 엔진
('study_elastic_011',
 (SELECT id FROM "User" WHERE email = 'shin@example.com' LIMIT 1),
 'Elasticsearch 검색 엔진 구축',
 '🔍',
 'Elasticsearch로 강력한 검색 기능을 구현합니다. 인덱싱, 쿼리 최적화, 집계 분석까지!',
 '프로그래밍',
 '검색엔진',
 16,
 true,
 true,
 true,
 4.6,
 20,
 ARRAY['Elasticsearch', '검색', '빅데이터'],
 'invite_elastic_011',
 NOW() - INTERVAL '16 days',
 NOW() - INTERVAL '16 days'),

-- 12. FastAPI 백엔드 개발
('study_fastapi_012',
 (SELECT id FROM "User" WHERE email = 'jo@example.com' LIMIT 1),
 'FastAPI 모던 백엔드 개발',
 '⚡',
 'Python FastAPI로 빠르고 현대적인 REST API를 개발합니다. 비동기, 타입힌트, 자동 문서화!',
 '프로그래밍',
 '백엔드',
 15,
 true,
 false,
 true,
 4.9,
 25,
 ARRAY['FastAPI', 'Python', 'REST API'],
 'invite_fastapi_012',
 NOW() - INTERVAL '7 days',
 NOW() - INTERVAL '7 days'),

-- 13. Three.js 3D 웹
('study_threejs_013',
 (SELECT id FROM "User" WHERE email = 'bae@example.com' LIMIT 1),
 'Three.js로 만드는 3D 웹',
 '🎨',
 'Three.js를 활용한 3D 웹 그래픽스 개발. WebGL, 셰이더, 인터랙티브 경험을 만듭니다.',
 '프로그래밍',
 '웹그래픽',
 12,
 true,
 true,
 true,
 4.7,
 16,
 ARRAY['Three.js', '3D', 'WebGL'],
 'invite_threejs_013',
 NOW() - INTERVAL '13 days',
 NOW() - INTERVAL '13 days'),

-- 14. NestJS 엔터프라이즈
('study_nestjs_014',
 (SELECT id FROM "User" WHERE email = 'song@example.com' LIMIT 1),
 'NestJS 엔터프라이즈 애플리케이션',
 '🐈',
 'NestJS로 확장 가능한 엔터프라이즈급 백엔드를 구축합니다. DI, 모듈 시스템, 마이크로서비스까지!',
 '프로그래밍',
 '백엔드',
 16,
 true,
 false,
 true,
 4.8,
 21,
 ARRAY['NestJS', 'Node.js', 'TypeScript'],
 'invite_nestjs_014',
 NOW() - INTERVAL '19 days',
 NOW() - INTERVAL '19 days'),

-- 15. PostgreSQL 고급 튜닝
('study_postgres_015',
 (SELECT id FROM "User" WHERE email = 'hong@example.com' LIMIT 1),
 'PostgreSQL 고급 튜닝 & 최적화',
 '🐘',
 'PostgreSQL의 고급 기능과 성능 튜닝을 마스터합니다. 쿼리 최적화, 파티셔닝, 복제까지!',
 '프로그래밍',
 '데이터베이스',
 14,
 true,
 true,
 true,
 4.7,
 18,
 ARRAY['PostgreSQL', 'SQL', '튜닝'],
 'invite_postgres_015',
 NOW() - INTERVAL '6 days',
 NOW() - INTERVAL '6 days'),

-- 16. Figma to Code
('study_figma_016',
 (SELECT id FROM "User" WHERE email = 'kwon@example.com' LIMIT 1),
 'Figma to Code - 디자인 구현',
 '🎨',
 'Figma 디자인을 실제 코드로 완벽하게 구현하는 방법을 배웁니다. 디자인 시스템, 컴포넌트화까지!',
 '프로그래밍',
 '프론트엔드',
 15,
 true,
 false,
 true,
 4.6,
 19,
 ARRAY['Figma', 'UI구현', '디자인'],
 'invite_figma_016',
 NOW() - INTERVAL '17 days',
 NOW() - INTERVAL '17 days'),

-- 17. RabbitMQ 메시지 큐
('study_rabbitmq_017',
 (SELECT id FROM "User" WHERE email = 'moon@example.com' LIMIT 1),
 'RabbitMQ 메시지 큐 시스템',
 '🐰',
 'RabbitMQ로 안정적인 메시지 큐 시스템을 구축합니다. 비동기 처리, 이벤트 드리븐 아키텍처!',
 '프로그래밍',
 '백엔드',
 12,
 true,
 true,
 true,
 4.5,
 13,
 ARRAY['RabbitMQ', '메시지큐', '비동기'],
 'invite_rabbitmq_017',
 NOW() - INTERVAL '21 days',
 NOW() - INTERVAL '21 days'),

-- 18. Tailwind CSS 마스터
('study_tailwind_018',
 (SELECT id FROM "User" WHERE email = 'ahn@example.com' LIMIT 1),
 'Tailwind CSS 완전정복',
 '💨',
 'Tailwind CSS로 빠르고 일관된 UI를 구축합니다. 커스터마이징, 반응형, 다크모드까지!',
 '프로그래밍',
 '프론트엔드',
 18,
 true,
 true,
 true,
 4.8,
 24,
 ARRAY['Tailwind', 'CSS', 'UI'],
 'invite_tailwind_018',
 NOW() - INTERVAL '5 days',
 NOW() - INTERVAL '5 days'),

-- 19. Playwright E2E 테스트
('study_playwright_019',
 (SELECT id FROM "User" WHERE email = 'kimy@example.com' LIMIT 1),
 'Playwright로 완성하는 E2E 테스트',
 '🎭',
 'Playwright를 활용한 안정적인 E2E 테스트 작성. 크로스 브라우저, 시각적 테스트까지!',
 '프로그래밍',
 '테스트',
 14,
 true,
 false,
 true,
 4.7,
 16,
 ARRAY['Playwright', 'E2E', '테스트'],
 'invite_playwright_019',
 NOW() - INTERVAL '10 days',
 NOW() - INTERVAL '10 days'),

-- 20. Go 동시성 프로그래밍
('study_go_020',
 (SELECT id FROM "User" WHERE email = 'leey@example.com' LIMIT 1),
 'Go 동시성 프로그래밍 마스터',
 '🐹',
 'Go의 고루틴과 채널을 활용한 동시성 프로그래밍을 마스터합니다. 고성능 서버 개발의 핵심!',
 '프로그래밍',
 '백엔드',
 16,
 true,
 true,
 true,
 4.9,
 22,
 ARRAY['Go', 'Golang', '동시성'],
 'invite_go_020',
 NOW() - INTERVAL '4 days',
 NOW() - INTERVAL '4 days');

-- 쿼리 실행 후 확인
SELECT COUNT(*) as total_studies FROM "Study";
SELECT name, emoji, category, "isRecruiting" FROM "Study" ORDER BY "createdAt" DESC LIMIT 25;

